---
# Playbook for identify some facts inside OS
- hosts: "{{ hosts | default('all') }}"
  become: true
  become_method: sudo
  gather_facts: yes
 
  tasks:
  - name: debug some server facts for identifiyng OS
    debug:
       msg:
       - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
       - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
       - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
